---
- name: Fjah1872 - Ansible Setup for MySQL DB
  hosts: my_container
  connection: docker
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_remote_tmp: /tmp

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      raw: service mysql start

    - name: Check if database exists
      raw: mysql -uroot -ppassword -e "SHOW DATABASES LIKE 'olist_db';"
      register: db_check
      ignore_errors: yes

    - name: Create database if not exists
      raw: mysql -uroot -ppassword -e "CREATE DATABASE olist_db;"
      when: db_check.stdout == ""

    - name: Copy the SQL file to the container
      copy:
        src: ./files/sql
        dest: /tmp/

    - name: Copy the CSV files to the container
      copy:
        src: ./files/csv/
        dest: /var/lib/mysql-files/

    - name: Run SQL file to load schema/data
      shell: |
        mysql --force -u root -ppassword olist_db < /tmp/sql/createdb.sql
      args:
        executable: /bin/bash